workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Build APK with Flutter
        script: |
          flutter build apk --release
